name: PHP CI

on:
  pull_request:
    branches: [maestro]
  # push:
  # branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

      - name: Run tests
        run: ./vendor/bin/pest
